name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job for pull requests - dry run
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch entire history like Azure pipeline
          
      - name: Git config user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
          
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
        
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
        
      - name: Rush Build
        run: node common/scripts/install-run-rush.js build
        
      - name: Rush Publish (Dry Run)
        run: |
          node common/scripts/install-run-rush.js publish --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
        
  # Job for main branch - actual publish
  publish-on-merge:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, 'Automatic commit of uncommitted changes')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch entire history
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Git config user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
          
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
        
      - name: Rush Update
        run: node common/scripts/install-run-rush.js update
        
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
        
      - name: Rush Build
        run: node common/scripts/install-run-rush.js build
        
      - name: Verify npm authentication
        run: |
          echo "Testing npm authentication..."
          npm whoami
          echo "Testing access to @labrador-sgd scope..."
          npm view @labrador-sgd/button
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
          
      - name: Rush Publish
        run: node common/scripts/install-run-rush.js publish --apply --publish --add-commit-details --set-access-level public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
          
      - name: Create Pull Request for version updates
        if: success()
        run: |
          # Check if there are any changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            # Create a new branch for the PR
            BRANCH_NAME="auto/version-updates-${{ github.run_id }}"
            git checkout -b $BRANCH_NAME
            
            # Stage and commit all changes
            git add .
            git commit -m "chore: update package versions after publish"
            
            # Push the branch
            git push origin $BRANCH_NAME
            
            # Create PR using GitHub CLI
            gh pr create \
              --title "Auto: Update package versions after publish" \
              --body "This PR contains automatic version updates after publishing packages.

            Build ID: ${{ github.run_id }}
            Commit: ${{ github.sha }}" \
              --base main \
              --head $BRANCH_NAME
          else
            echo "No changes to commit, skipping PR creation"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display logs on failure
        if: failure()
        run: |
          echo "Displaying contents of npm log files:"
          find . -name "*.log" -type f -exec echo "Contents of {}:" \; -exec cat {} \; -exec echo "--------------------------------" \;
          
          # Also check common Rush log locations
          if [ -d "common/temp" ]; then
            echo "Contents of common/temp directory:"
            ls -la common/temp/
            find common/temp -name "*.log" -type f -exec echo "Contents of {}:" \; -exec cat {} \; -exec echo "--------------------------------" \;
          fi